packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - electron
  - fsevents

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - core-js
  - esbuild
  - msgpackr-extract
